model: 'medical'
network: 'ro_34'
task: 'snake'
resume: true
gpus: (0, 1, 2, 3, 4, 5, 6, 7)

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120)
    gamma: 0.25
    batch_size: 24
    dataset: 'MedicalTrain'
    num_workers: 32
    epoch: 150
    scheduler: 'manual'
    gammas: [0.5, 0.1]
test:
    dataset: 'MedicalTest'
    batch_size: 1

heads: {'ct_hm': 2, 'wh': 2}
segm_or_bbox: 'segm'
